// Generated by gencpp from file lio_sam/SLAMRequest.msg
// DO NOT EDIT!


#ifndef LIO_SAM_MESSAGE_SLAMREQUEST_H
#define LIO_SAM_MESSAGE_SLAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lio_sam
{
template <class ContainerAllocator>
struct SLAMRequest_
{
  typedef SLAMRequest_<ContainerAllocator> Type;

  SLAMRequest_()
    : timeSteps()  {
    }
  SLAMRequest_(const ContainerAllocator& _alloc)
    : timeSteps(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _timeSteps_type;
  _timeSteps_type timeSteps;





  typedef boost::shared_ptr< ::lio_sam::SLAMRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lio_sam::SLAMRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SLAMRequest_

typedef ::lio_sam::SLAMRequest_<std::allocator<void> > SLAMRequest;

typedef boost::shared_ptr< ::lio_sam::SLAMRequest > SLAMRequestPtr;
typedef boost::shared_ptr< ::lio_sam::SLAMRequest const> SLAMRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lio_sam::SLAMRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lio_sam::SLAMRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lio_sam::SLAMRequest_<ContainerAllocator1> & lhs, const ::lio_sam::SLAMRequest_<ContainerAllocator2> & rhs)
{
  return lhs.timeSteps == rhs.timeSteps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lio_sam::SLAMRequest_<ContainerAllocator1> & lhs, const ::lio_sam::SLAMRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lio_sam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lio_sam::SLAMRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lio_sam::SLAMRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lio_sam::SLAMRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lio_sam::SLAMRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lio_sam::SLAMRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lio_sam::SLAMRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lio_sam::SLAMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22beaa9729a4d342620b03d0ce0a3db3";
  }

  static const char* value(const ::lio_sam::SLAMRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22beaa9729a4d342ULL;
  static const uint64_t static_value2 = 0x620b03d0ce0a3db3ULL;
};

template<class ContainerAllocator>
struct DataType< ::lio_sam::SLAMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lio_sam/SLAMRequest";
  }

  static const char* value(const ::lio_sam::SLAMRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lio_sam::SLAMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] timeSteps\n"
;
  }

  static const char* value(const ::lio_sam::SLAMRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lio_sam::SLAMRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeSteps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SLAMRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lio_sam::SLAMRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lio_sam::SLAMRequest_<ContainerAllocator>& v)
  {
    s << indent << "timeSteps[]" << std::endl;
    for (size_t i = 0; i < v.timeSteps.size(); ++i)
    {
      s << indent << "  timeSteps[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.timeSteps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIO_SAM_MESSAGE_SLAMREQUEST_H
